version: '3.8'

services:
  kratos-postgres:
    image: postgres:15-alpine
    container_name: kratos-postgres
    networks:
      - ory-net
    environment:
      POSTGRES_DB: kratos
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ory_kratos_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kratos"]
      interval: 10s
      timeout: 5s
      retries: 5

  kratos:
    build: ../
    container_name: kratos
    networks:
      - ory-net
    ports:
      - "4433:4433"  # Public API
      - "4434:4434"  # Admin API
    environment:
      - DSN=postgres://kratos:password@kratos-postgres:5432/kratos?sslmode=disable
      - KRATOS_PUBLIC_URL=http://localhost:4433
      - SELF_SERVICE_UI_URL=http://localhost:3000
      - DEFAULT_SECRET=131c95bfb82eef1d206c606835c657c8
      - COOKIE_SECRET=131c95bfb82eef1d206c606835c657c8
      - CIPHER_SECRET=966371e76754558d9692262589f85bc0
      - OIDC_PROVIDERS_GOOGLE_CLIENT_ID=XXX
      - OIDC_PROVIDERS_GOOGLE_CLIENT_SECRET=XXX
      - DOMAIN_COOKIE=localhost
      - OAUTH2_PROVIDER_URL=http://hydra:4445
      - LOG_LEVEL=debug
      - KRATOS_EXTRA_ARGS=--dev
      - RUN_MIGRATIONS=true
    depends_on:
      kratos-postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ory_kratos_postgres_data:

networks:
  ory-net:
    external: true
